version: "3"
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    env_file:
      - production.env
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres
    env_file:
      - production.env
    ports:
      - 5432:5432

  payments:
    image: livsmichael/p2py:1.0.4
    restart: always
    ports:
      - 8000:8000
    env_file:
      - production.env
    command: >
      sh -c "sleep 5 && uvicorn payment_service.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"

    depends_on:
      - postgres
      - zookeeper
      - kafka
    labels:
      kompose.service.type: LoadBalancer
      kompose.image-pull-policy: Always

  producer:
    image: livsmichael/p2py:1.0.4
    restart: always
    ports:
      - 9000:9000
    env_file:
      - production.env
    depends_on:
      - postgres
      - zookeeper
      - kafka
    command: >
      sh -c "sleep 5 && uvicorn producer_service.app.main:app --reload --workers 1 --host 0.0.0.0 --port 9000"

  risk-engine:
    image: livsmichael/p2py:1.0.4
    restart: always
    env_file:
      - production.env
    depends_on:
      - postgres
      - zookeeper
      - kafka
    command: >
      sh -c "sleep 5 && python risk_engine_service/main.py"


