from os import environ
from pathlib import Path

from common.logger import get_logger

logger = get_logger(__file__)

ROOT_DIR = Path(__file__).parent.parent.absolute()

# Postgres configuration
POSTGRES_USERNAME = environ.get("POSTGRES_USERNAME", "docker")
POSTGRES_PASSWORD = environ.get("POSTGRES_PASSWORD", "docker")
POSTGRES_HOST = environ.get("POSTGRES_HOST", "localhost")
POSTGRES_PORT = environ.get("POSTGRES_PORT", 5432)
DATABASE_URL = f"postgresql://{POSTGRES_USERNAME}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/p2pay"

# Kafka configuration
PROJECT_NAME: str = environ.get("PROJECT_NAME", "P2PY")
KAFKA_TOPIC = environ.get("KAFKA_TOPIC", "payments")
KAFKA_HOST: str = environ.get("KAFKA_HOST", "kafka")
KAFKA_PORT: str = environ.get("KAFKA_PORT", 9092)
KAFKA_BOOTSTRAP_SERVERS = f"{KAFKA_HOST}:{KAFKA_PORT}"
KAFKA_CONSUMER_GROUP = environ.get("KAFKA_CONSUMER_GROUP", "group")

# Payments URI
PAYMENTS_HOST = environ.get("PAYMENTS_HOST", "localhost")
PAYMENTS_PORT = environ.get("PAYMENTS_PORT", 8000)
PAYMENTS_URI = f"http://{PAYMENTS_HOST}:{PAYMENTS_PORT}/api/v1/payments"

# Producer URI
PRODUCER_HOST = environ.get("PRODUCER_HOST", "localhost")
PRODUCER_PORT = environ.get("PRODUCER_PORT", 8005)
PRODUCER_URI = f"http://{PRODUCER_HOST}:{PRODUCER_PORT}/api/v1/producer/{KAFKA_TOPIC}"

logger.info(
    f"""
ROOT_DIR={ROOT_DIR}
POSTGRES_USERNAME={POSTGRES_USERNAME}
POSTGRES_PASSWORD={POSTGRES_PASSWORD}
POSTGRES_HOST={POSTGRES_HOST}
POSTGRES_PORT={POSTGRES_PORT}
DATABASE_URL={DATABASE_URL}
PROJECT_NAME={PROJECT_NAME}
KAFKA_TOPIC={KAFKA_TOPIC}
KAFKA_HOST={KAFKA_HOST}
KAFKA_PORT={KAFKA_PORT}
KAFKA_BOOTSTRAP_SERVERS={KAFKA_BOOTSTRAP_SERVERS}
KAFKA_CONSUMER_GROUP={KAFKA_CONSUMER_GROUP}
PAYMENTS_HOST={PAYMENTS_HOST}
PAYMENTS_PORT={PAYMENTS_PORT}
PAYMENTS_URI={PAYMENTS_URI}
PRODUCER_HOST={PRODUCER_HOST}
PRODUCER_PORT={PRODUCER_PORT}
PRODUCER_URI={PRODUCER_URI}
"""
)
